"""Semantic-IDE error codes."""

E_INTENT_PARSE = "E_INTENT_PARSE"
E_SCHEMA_INVALID = "E_SCHEMA_INVALID"
E_AST_NO_DT = "E_AST_NO_DT"
E_EXPLAIN_FAIL = "E_EXPLAIN_FAIL"
E_SINK_WRITE = "E_SINK_WRITE"
E_CODEGEN_FAIL = "E_CODEGEN_FAIL"
